import { ColorScale } from "../domain/domain";
import { getHue, makeHex } from "../domain/hex";
import { makeHue } from "../domain/hue";
import { ColoredHue } from "../domain/types";

/**
 * Generates CSS color variables template
 * @param {ColorScale[]} palette palette object generated by user choosing color
 */
export function generateCssVariables(palette: ColorScale[]): string {
  let variables = "";

  palette.forEach(({ colorName, shades }) => {
    shades.forEach(({ weight, hexValue }) => {
      variables += `--${colorName}-${weight}: ${hexValue};\n`;
    });
    variables += "\n";
  });

  return variables.trim(); // Remove the trailing newline for clean output
}

const coloredHues: ColoredHue[] = [
  { colorName: "red", hue: makeHue(0) },
  { colorName: "green", hue: makeHue(120) },
  { colorName: "blue", hue: makeHue(240) },
];

export function generateCode(hexCode: string): string {
  // get hue
  const hex = makeHex(hexCode);
  const hue = getHue(hex);
  return hexCode;
}
