import { createPalette } from "./createPalette";
import { ColorScale } from "./domain";

/**
 * Generates CSS color variables template
 * @param {ColorScale[]} palette palette object generated by user choosing color
 */
function generateCssVariables(palette: ColorScale[]): string {
  let variables = "";

  palette.forEach(({ colorName, shades }) => {
    shades.forEach(({ weight, hexValue }) => {
      variables += `--${colorName}-${weight}: ${hexValue};\n`;
    });
    variables += "\n";
  });

  return variables.trim(); // Remove the trailing newline for clean output
}

export { generateCssVariables };
