import {
    generateFrameworkObject
} from "./createPalette.js";



/**
 * Generates CSS color variables template
 * @param {object} palette palette object generated by user choosing color
 */
function generateCssVariables(palette) {
    const frameworkObject = generateFrameworkObject(palette);
    let variables = "";
    for (const color in frameworkObject) {
        variables += "\n";
        for (const [shade, hex] of Object.entries(frameworkObject[color])) {
            variables += `--${color}-${shade}: ${hex}; \n`;
        }
    }

    const cssCode = `${variables}`

    return cssCode
}

export {
    generateCssVariables
}